<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CountryLanguage', 'doctrine');

/**
 * BaseCountryLanguage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $countrycode
 * @property string $language
 * @property enum $isofficial
 * @property float $percentage
 * @property Country $Country
 * 
 * @method string          getCountrycode() Returns the current record's "countrycode" value
 * @method string          getLanguage()    Returns the current record's "language" value
 * @method enum            getIsofficial()  Returns the current record's "isofficial" value
 * @method float           getPercentage()  Returns the current record's "percentage" value
 * @method Country         getCountry()     Returns the current record's "Country" value
 * @method CountryLanguage setCountrycode() Sets the current record's "countrycode" value
 * @method CountryLanguage setLanguage()    Sets the current record's "language" value
 * @method CountryLanguage setIsofficial()  Sets the current record's "isofficial" value
 * @method CountryLanguage setPercentage()  Sets the current record's "percentage" value
 * @method CountryLanguage setCountry()     Sets the current record's "Country" value
 * 
 * @package    homewww
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCountryLanguage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('CountryLanguage');
        $this->hasColumn('countrycode', 'string', 3, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('language', 'string', 30, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('isofficial', 'enum', 1, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'T',
              1 => 'F',
             ),
             'primary' => false,
             'default' => 'F',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('percentage', 'float', 4, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Country', array(
             'local' => 'countrycode',
             'foreign' => 'code'));
    }
}