<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('JtZipcodes', 'doctrine');

/**
 * BaseJtZipcodes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $zip
 * @property string $city
 * @property string $state
 * @property float $latitude
 * @property float $longitude
 * @property integer $timezone
 * @property integer $dst
 * 
 * @method integer    get()          Returns the current record's "id" value
 * @method string     get()          Returns the current record's "zip" value
 * @method string     get()          Returns the current record's "city" value
 * @method string     get()          Returns the current record's "state" value
 * @method float      get()          Returns the current record's "latitude" value
 * @method float      get()          Returns the current record's "longitude" value
 * @method integer    get()          Returns the current record's "timezone" value
 * @method integer    get()          Returns the current record's "dst" value
 * @method JtZipcodes set()          Sets the current record's "id" value
 * @method JtZipcodes set()          Sets the current record's "zip" value
 * @method JtZipcodes set()          Sets the current record's "city" value
 * @method JtZipcodes set()          Sets the current record's "state" value
 * @method JtZipcodes set()          Sets the current record's "latitude" value
 * @method JtZipcodes set()          Sets the current record's "longitude" value
 * @method JtZipcodes set()          Sets the current record's "timezone" value
 * @method JtZipcodes set()          Sets the current record's "dst" value
 * 
 * @package    jtweb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJtZipcodes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('JtZipcodes');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('zip', 'string', 5, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 5,
             ));
        $this->hasColumn('city', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('state', 'string', 5, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 5,
             ));
        $this->hasColumn('latitude', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('longitude', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('timezone', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('dst', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}