<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('JtLinks', 'doctrine');

/**
 * BaseJtLinks
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $lid
 * @property string $text
 * @property string $url
 * @property string $cat
 * @property string $public
 * 
 * @method integer getid()     Returns the current record's "id" value
 * @method string  getlid()    Returns the current record's "lid" value
 * @method string  gettext()   Returns the current record's "text" value
 * @method string  geturl()    Returns the current record's "url" value
 * @method string  getcat()    Returns the current record's "cat" value
 * @method string  getpublic() Returns the current record's "public" value
 * @method JtLinks setid()     Sets the current record's "id" value
 * @method JtLinks setlid()    Sets the current record's "lid" value
 * @method JtLinks settext()   Sets the current record's "text" value
 * @method JtLinks seturl()    Sets the current record's "url" value
 * @method JtLinks setcat()    Sets the current record's "cat" value
 * @method JtLinks setpublic() Sets the current record's "public" value
 * 
 * @package    jtweb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJtLinks extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('JtLinks');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('lid', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('text', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('url', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('cat', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('public', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}