<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('JtPosts', 'doctrine');

/**
 * BaseJtPosts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $post_author
 * @property timestamp $post_date
 * @property string $post_content
 * @property string $post_title
 * @property string $post_status
 * @property timestamp $post_modified
 * 
 * @method integer   getid()            Returns the current record's "id" value
 * @method integer   getpost_author()   Returns the current record's "post_author" value
 * @method timestamp getpost_date()     Returns the current record's "post_date" value
 * @method string    getpost_content()  Returns the current record's "post_content" value
 * @method string    getpost_title()    Returns the current record's "post_title" value
 * @method string    getpost_status()   Returns the current record's "post_status" value
 * @method timestamp getpost_modified() Returns the current record's "post_modified" value
 * @method JtPosts   setid()            Sets the current record's "id" value
 * @method JtPosts   setpost_author()   Sets the current record's "post_author" value
 * @method JtPosts   setpost_date()     Sets the current record's "post_date" value
 * @method JtPosts   setpost_content()  Sets the current record's "post_content" value
 * @method JtPosts   setpost_title()    Sets the current record's "post_title" value
 * @method JtPosts   setpost_status()   Sets the current record's "post_status" value
 * @method JtPosts   setpost_modified() Sets the current record's "post_modified" value
 * 
 * @package    jtweb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJtPosts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('JtPosts');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('post_author', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('post_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('post_content', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('post_title', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('post_status', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'publish',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('post_modified', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}