<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('JtTermTaxonomy', 'doctrine');

/**
 * BaseJtTermTaxonomy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $term_taxonomy_id
 * @property integer $term_id
 * @property string $taxonomy
 * @property string $description
 * @property integer $parent
 * @property integer $count
 * 
 * @method integer        getTermTaxonomyId()   Returns the current record's "term_taxonomy_id" value
 * @method integer        getTermId()           Returns the current record's "term_id" value
 * @method string         getTaxonomy()         Returns the current record's "taxonomy" value
 * @method string         getDescription()      Returns the current record's "description" value
 * @method integer        getParent()           Returns the current record's "parent" value
 * @method integer        getCount()            Returns the current record's "count" value
 * @method JtTermTaxonomy setTermTaxonomyId()   Sets the current record's "term_taxonomy_id" value
 * @method JtTermTaxonomy setTermId()           Sets the current record's "term_id" value
 * @method JtTermTaxonomy setTaxonomy()         Sets the current record's "taxonomy" value
 * @method JtTermTaxonomy setDescription()      Sets the current record's "description" value
 * @method JtTermTaxonomy setParent()           Sets the current record's "parent" value
 * @method JtTermTaxonomy setCount()            Sets the current record's "count" value
 * 
 * @package    homewww
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJtTermTaxonomy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('JtTermTaxonomy');
        $this->hasColumn('term_taxonomy_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('term_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('taxonomy', 'string', 32, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 32,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('parent', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('count', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}