<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('JtGeodata', 'doctrine');

/**
 * BaseJtGeodata
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $geoip_addr
 * @property string $geoip_continent_code
 * @property string $geoip_country_code
 * @property string $geoip_country_name
 * @property string $geoip_city
 * @property string $geoip_region
 * @property string $geoip_region_name
 * @property string $geoip_dma_code
 * @property string $geoip_metro_code
 * @property string $geoip_area_code
 * @property float $geoip_latitude
 * @property float $geoip_longitude
 * @property timestamp $created
 * 
 * @method integer   getid()                   Returns the current record's "id" value
 * @method string    getgeoip_addr()           Returns the current record's "geoip_addr" value
 * @method string    getgeoip_continent_code() Returns the current record's "geoip_continent_code" value
 * @method string    getgeoip_country_code()   Returns the current record's "geoip_country_code" value
 * @method string    getgeoip_country_name()   Returns the current record's "geoip_country_name" value
 * @method string    getgeoip_city()           Returns the current record's "geoip_city" value
 * @method string    getgeoip_region()         Returns the current record's "geoip_region" value
 * @method string    getgeoip_region_name()    Returns the current record's "geoip_region_name" value
 * @method string    getgeoip_dma_code()       Returns the current record's "geoip_dma_code" value
 * @method string    getgeoip_metro_code()     Returns the current record's "geoip_metro_code" value
 * @method string    getgeoip_area_code()      Returns the current record's "geoip_area_code" value
 * @method float     getgeoip_latitude()       Returns the current record's "geoip_latitude" value
 * @method float     getgeoip_longitude()      Returns the current record's "geoip_longitude" value
 * @method timestamp getcreated()              Returns the current record's "created" value
 * @method JtGeodata setid()                   Sets the current record's "id" value
 * @method JtGeodata setgeoip_addr()           Sets the current record's "geoip_addr" value
 * @method JtGeodata setgeoip_continent_code() Sets the current record's "geoip_continent_code" value
 * @method JtGeodata setgeoip_country_code()   Sets the current record's "geoip_country_code" value
 * @method JtGeodata setgeoip_country_name()   Sets the current record's "geoip_country_name" value
 * @method JtGeodata setgeoip_city()           Sets the current record's "geoip_city" value
 * @method JtGeodata setgeoip_region()         Sets the current record's "geoip_region" value
 * @method JtGeodata setgeoip_region_name()    Sets the current record's "geoip_region_name" value
 * @method JtGeodata setgeoip_dma_code()       Sets the current record's "geoip_dma_code" value
 * @method JtGeodata setgeoip_metro_code()     Sets the current record's "geoip_metro_code" value
 * @method JtGeodata setgeoip_area_code()      Sets the current record's "geoip_area_code" value
 * @method JtGeodata setgeoip_latitude()       Sets the current record's "geoip_latitude" value
 * @method JtGeodata setgeoip_longitude()      Sets the current record's "geoip_longitude" value
 * @method JtGeodata setcreated()              Sets the current record's "created" value
 * 
 * @package    jtweb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJtGeodata extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('JtGeodata');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('geoip_addr', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('geoip_continent_code', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('geoip_country_code', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('geoip_country_name', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('geoip_city', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('geoip_region', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('geoip_region_name', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('geoip_dma_code', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('geoip_metro_code', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('geoip_area_code', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('geoip_latitude', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('geoip_longitude', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}