<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Test2', 'doctrine');

/**
 * BaseTest2
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descr
 * 
 * @method integer getId()    Returns the current record's "id" value
 * @method string  getDescr() Returns the current record's "descr" value
 * @method Test2   setId()    Sets the current record's "id" value
 * @method Test2   setDescr() Sets the current record's "descr" value
 * 
 * @package    homewww
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTest2 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('test2');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('descr', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}