<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('JtPosts', 'doctrine');

/**
 * BaseJtPosts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $post_author
 * @property timestamp $post_date
 * @property timestamp $post_date_gmt
 * @property string $post_content
 * @property string $post_title
 * @property string $post_excerpt
 * @property string $post_status
 * @property string $comment_status
 * @property string $ping_status
 * @property string $post_password
 * @property string $post_name
 * @property string $to_ping
 * @property string $pinged
 * @property timestamp $post_modified
 * @property timestamp $post_modified_gmt
 * @property string $post_content_filtered
 * @property integer $post_parent
 * @property string $guid
 * @property integer $menu_order
 * @property string $post_type
 * @property string $post_mime_type
 * @property integer $comment_count
 * 
 * @method integer   getId()                    Returns the current record's "id" value
 * @method integer   getPostAuthor()            Returns the current record's "post_author" value
 * @method timestamp getPostDate()              Returns the current record's "post_date" value
 * @method timestamp getPostDateGmt()           Returns the current record's "post_date_gmt" value
 * @method string    getPostContent()           Returns the current record's "post_content" value
 * @method string    getPostTitle()             Returns the current record's "post_title" value
 * @method string    getPostExcerpt()           Returns the current record's "post_excerpt" value
 * @method string    getPostStatus()            Returns the current record's "post_status" value
 * @method string    getCommentStatus()         Returns the current record's "comment_status" value
 * @method string    getPingStatus()            Returns the current record's "ping_status" value
 * @method string    getPostPassword()          Returns the current record's "post_password" value
 * @method string    getPostName()              Returns the current record's "post_name" value
 * @method string    getToPing()                Returns the current record's "to_ping" value
 * @method string    getPinged()                Returns the current record's "pinged" value
 * @method timestamp getPostModified()          Returns the current record's "post_modified" value
 * @method timestamp getPostModifiedGmt()       Returns the current record's "post_modified_gmt" value
 * @method string    getPostContentFiltered()   Returns the current record's "post_content_filtered" value
 * @method integer   getPostParent()            Returns the current record's "post_parent" value
 * @method string    getGuid()                  Returns the current record's "guid" value
 * @method integer   getMenuOrder()             Returns the current record's "menu_order" value
 * @method string    getPostType()              Returns the current record's "post_type" value
 * @method string    getPostMimeType()          Returns the current record's "post_mime_type" value
 * @method integer   getCommentCount()          Returns the current record's "comment_count" value
 * @method JtPosts   setId()                    Sets the current record's "id" value
 * @method JtPosts   setPostAuthor()            Sets the current record's "post_author" value
 * @method JtPosts   setPostDate()              Sets the current record's "post_date" value
 * @method JtPosts   setPostDateGmt()           Sets the current record's "post_date_gmt" value
 * @method JtPosts   setPostContent()           Sets the current record's "post_content" value
 * @method JtPosts   setPostTitle()             Sets the current record's "post_title" value
 * @method JtPosts   setPostExcerpt()           Sets the current record's "post_excerpt" value
 * @method JtPosts   setPostStatus()            Sets the current record's "post_status" value
 * @method JtPosts   setCommentStatus()         Sets the current record's "comment_status" value
 * @method JtPosts   setPingStatus()            Sets the current record's "ping_status" value
 * @method JtPosts   setPostPassword()          Sets the current record's "post_password" value
 * @method JtPosts   setPostName()              Sets the current record's "post_name" value
 * @method JtPosts   setToPing()                Sets the current record's "to_ping" value
 * @method JtPosts   setPinged()                Sets the current record's "pinged" value
 * @method JtPosts   setPostModified()          Sets the current record's "post_modified" value
 * @method JtPosts   setPostModifiedGmt()       Sets the current record's "post_modified_gmt" value
 * @method JtPosts   setPostContentFiltered()   Sets the current record's "post_content_filtered" value
 * @method JtPosts   setPostParent()            Sets the current record's "post_parent" value
 * @method JtPosts   setGuid()                  Sets the current record's "guid" value
 * @method JtPosts   setMenuOrder()             Sets the current record's "menu_order" value
 * @method JtPosts   setPostType()              Sets the current record's "post_type" value
 * @method JtPosts   setPostMimeType()          Sets the current record's "post_mime_type" value
 * @method JtPosts   setCommentCount()          Sets the current record's "comment_count" value
 * 
 * @package    homewww
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJtPosts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('JtPosts');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('post_author', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('post_date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('post_date_gmt', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('post_content', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('post_title', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('post_excerpt', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('post_status', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'publish',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('comment_status', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'open',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('ping_status', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'open',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('post_password', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('post_name', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('to_ping', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('pinged', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('post_modified', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('post_modified_gmt', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('post_content_filtered', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('post_parent', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('guid', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('menu_order', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('post_type', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'post',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('post_mime_type', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('comment_count', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}