<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('JtQuotes', 'doctrine');

/**
 * BaseJtQuotes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $text
 * @property string $source
 * @property string $link
 * 
 * @method integer  getid()     Returns the current record's "id" value
 * @method string   gettext()   Returns the current record's "text" value
 * @method string   getsource() Returns the current record's "source" value
 * @method string   getlink()   Returns the current record's "link" value
 * @method JtQuotes setid()     Sets the current record's "id" value
 * @method JtQuotes settext()   Sets the current record's "text" value
 * @method JtQuotes setsource() Sets the current record's "source" value
 * @method JtQuotes setlink()   Sets the current record's "link" value
 * 
 * @package    jtweb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJtQuotes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('JtQuotes');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('source', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('link', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}