<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('JtCountryLanguage', 'doctrine');

/**
 * BaseJtCountryLanguage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $countrycode
 * @property string $language
 * @property enum $isofficial
 * @property float $percentage
 * @property JtCountry $JtCountry
 * 
 * @method string            get()            Returns the current record's "countrycode" value
 * @method string            get()            Returns the current record's "language" value
 * @method enum              get()            Returns the current record's "isofficial" value
 * @method float             get()            Returns the current record's "percentage" value
 * @method JtCountry         get()            Returns the current record's "JtCountry" value
 * @method JtCountryLanguage set()            Sets the current record's "countrycode" value
 * @method JtCountryLanguage set()            Sets the current record's "language" value
 * @method JtCountryLanguage set()            Sets the current record's "isofficial" value
 * @method JtCountryLanguage set()            Sets the current record's "percentage" value
 * @method JtCountryLanguage set()            Sets the current record's "JtCountry" value
 * 
 * @package    jtweb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJtCountryLanguage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('JtCountryLanguage');
        $this->hasColumn('countrycode', 'string', 3, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('language', 'string', 30, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('isofficial', 'enum', 1, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'T',
              1 => 'F',
             ),
             'primary' => false,
             'default' => 'F',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('percentage', 'float', 4, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('JtCountry', array(
             'local' => 'countrycode',
             'foreign' => 'code'));
    }
}