<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('JtTerms', 'doctrine');

/**
 * BaseJtTerms
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $term_id
 * @property string $name
 * @property string $slug
 * @property integer $term_group
 * 
 * @method integer getTermId()     Returns the current record's "term_id" value
 * @method string  getName()       Returns the current record's "name" value
 * @method string  getSlug()       Returns the current record's "slug" value
 * @method integer getTermGroup()  Returns the current record's "term_group" value
 * @method JtTerms setTermId()     Sets the current record's "term_id" value
 * @method JtTerms setName()       Sets the current record's "name" value
 * @method JtTerms setSlug()       Sets the current record's "slug" value
 * @method JtTerms setTermGroup()  Sets the current record's "term_group" value
 * 
 * @package    jtweb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJtTerms extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('JtTerms');
        $this->hasColumn('term_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('slug', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('term_group', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}