<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('JtTermRelationships', 'doctrine');

/**
 * BaseJtTermRelationships
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $object_id
 * @property integer $term_taxonomy_id
 * @property integer $term_order
 * 
 * @method integer             getObjectId()         Returns the current record's "object_id" value
 * @method integer             getTermTaxonomyId()   Returns the current record's "term_taxonomy_id" value
 * @method integer             getTermOrder()        Returns the current record's "term_order" value
 * @method JtTermRelationships setObjectId()         Sets the current record's "object_id" value
 * @method JtTermRelationships setTermTaxonomyId()   Sets the current record's "term_taxonomy_id" value
 * @method JtTermRelationships setTermOrder()        Sets the current record's "term_order" value
 * 
 * @package    jtweb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJtTermRelationships extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('JtTermRelationships');
        $this->hasColumn('object_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('term_taxonomy_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('term_order', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}