<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('JtTermTaxonomy', 'doctrine');

/**
 * BaseJtTermTaxonomy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $term_taxonomy_id
 * @property integer $term_id
 * @property string $taxonomy
 * @property string $description
 * @property integer $parent
 * @property integer $count
 * 
 * @method integer        getterm_taxonomy_id() Returns the current record's "term_taxonomy_id" value
 * @method integer        getterm_id()          Returns the current record's "term_id" value
 * @method string         gettaxonomy()         Returns the current record's "taxonomy" value
 * @method string         getdescription()      Returns the current record's "description" value
 * @method integer        getparent()           Returns the current record's "parent" value
 * @method integer        getcount()            Returns the current record's "count" value
 * @method JtTermTaxonomy setterm_taxonomy_id() Sets the current record's "term_taxonomy_id" value
 * @method JtTermTaxonomy setterm_id()          Sets the current record's "term_id" value
 * @method JtTermTaxonomy settaxonomy()         Sets the current record's "taxonomy" value
 * @method JtTermTaxonomy setdescription()      Sets the current record's "description" value
 * @method JtTermTaxonomy setparent()           Sets the current record's "parent" value
 * @method JtTermTaxonomy setcount()            Sets the current record's "count" value
 * 
 * @package    jtweb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJtTermTaxonomy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('JtTermTaxonomy');
        $this->hasColumn('term_taxonomy_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('term_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('taxonomy', 'string', 32, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 32,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('parent', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('count', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}