<?php

/**
 * AnnualReportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnnualReportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnnualReportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AnnualReport');
    }
}