<?php

/**
 * ChipotleOrdersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChipotleOrdersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChipotleOrdersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChipotleOrders');
    }
}