<?php

/**
 * CountryLanguageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CountryLanguageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CountryLanguageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CountryLanguage');
    }
}