<?php

/**
 * JtAnnualReportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JtAnnualReportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JtAnnualReportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JtAnnualReport');
    }
}