<?php

/**
 * JtCityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JtCityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JtCityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JtCity');
    }
}