<?php

/**
 * JtCountryLanguageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JtCountryLanguageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JtCountryLanguageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JtCountryLanguage');
    }
}