<?php

/**
 * JtMarathonResultsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JtMarathonResultsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JtMarathonResultsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JtMarathonResults');
    }
public static function getAll(){
	$vals=Doctrine_Core::getTable('JtMarathonResults')->findAll();
return $vals; 
	}

}
