<?php

/**
 * JtQuotesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JtQuotesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JtQuotesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JtQuotes');
    }
}