<?php

/**
 * JtTermTaxonomyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JtTermTaxonomyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JtTermTaxonomyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JtTermTaxonomy');
    }
}