<?php

/**
 * JtTermRelationshipsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JtTermRelationshipsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JtTermRelationshipsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JtTermRelationships');
    }
}