<?php

/**
 * JtTermsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JtTermsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JtTermsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JtTerms');
    }
}