<?php

/**
 * JtUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JtUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JtUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JtUsers');
    }
}