<?php

/**
 * JtWhoisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JtWhoisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JtWhoisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JtWhois');
    }
}