<?php

/**
 * JtZipcodesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JtZipcodesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JtZipcodesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JtZipcodes');
    }
}