<?php

/**
 * JtZipcodesExpandedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JtZipcodesExpandedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JtZipcodesExpandedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JtZipcodesExpanded');
    }
}