<?php

/**
 * JtZipcodesRevisedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JtZipcodesRevisedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JtZipcodesRevisedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JtZipcodesRevised');
    }
}