<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/12/30 15:15:26

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:unix_socket=/var/run/mysqld/mysqld.sock;dbname=symfony',
  'username' => 'root',
  'password' => 'lowder123!!',
  'name' => 'doctrine',
)),);
