autoload:
  ar_php:
    path: /var/jt-web/lib/I18N/
    recursive: on
  fb:
    path: /var/jt-web/lib/Facebook/
    recursive: on
#  csv:
#    path: /var/jt-web/lib/php-csv-utils-0.3/Csv/
#    recursive: on
#  tcpdf:
#    path: /var/jt-web/lib/tcpdf/Csv/
#    recursive: on
#  jpgraph:
#    path: /var/jt-web/lib/jpgraph-3.5.0b1/src/
#    recursive: on
    
