generator:
  class: sfDoctrineGenerator
  param:
    model_class:           JtTerms
    theme:                 admin
    non_verbose_templates: true
    with_show:             true
    singular:              terms
    plural:                jt_terms_list
    route_prefix:          jt_terms
    with_doctrine_route:   true
    actions_base_class:    sfActions
    config:  
      actions: ~
      fields:
        post_title:    {  }
        post_date : { }
        post_content : { }
      list:
        display:  [term_id, name, slug, term_group] 
      edit: ~
      filter: ~
      form: ~ 
      new: ~ 
